### ISSUE TITLE
Implementing create a new todo by context menu

### ISSUE THREAD

**Issue by aivinog1** [aivinog1/0pdd-idea-plugin#15]
Needs to able to create in all files a todo by Alt+Enter.

**Comment by 0pdd** [comment]
@aivinog1 4 puzzles [#37](https://github.com/aivinog1/0pdd-idea-plugin/issues/37), [#38](https://github.com/aivinog1/0pdd-idea-plugin/issues/38), [#39](https://github.com/aivinog1/0pdd-idea-plugin/issues/39), [#40](https://github.com/aivinog1/0pdd-idea-plugin/issues/40) are still not solved.

**Comment by aivinog1** [comment]
Let's close this. Todos were created.

**Comment by 0pdd** [comment]
@aivinog1 5 puzzles [#37](https://github.com/aivinog1/0pdd-idea-plugin/issues/37), [#39](https://github.com/aivinog1/0pdd-idea-plugin/issues/39), [#40](https://github.com/aivinog1/0pdd-idea-plugin/issues/40), [#44](https://github.com/aivinog1/0pdd-idea-plugin/issues/44), [#45](https://github.com/aivinog1/0pdd-idea-plugin/issues/45) are still not solved; solved: [#38](https://github.com/aivinog1/0pdd-idea-plugin/issues/38).
