### ISSUE TITLE
Let's move to the Kotlin

### ISSUE THREAD

**Issue by aivinog1** [aivinog1/0pdd-idea-plugin#26]
For now, the Kotling language is supported for creating plugins: https://www.jetbrains.org/intellij/sdk/docs/tutorials/kotlin.html

Let's move to it.

**Comment by 0pdd** [comment]
@aivinog1 2 puzzles [#28](https://github.com/aivinog1/0pdd-idea-plugin/issues/28), [#29](https://github.com/aivinog1/0pdd-idea-plugin/issues/29) are still not solved.

**Comment by aivinog1** [comment]
TODOs were created, let's close it for now.

**Comment by 0pdd** [comment]
@aivinog1 the puzzle [#28](https://github.com/aivinog1/0pdd-idea-plugin/issues/28) is still not solved; solved: [#29](https://github.com/aivinog1/0pdd-idea-plugin/issues/29).
